/**
 * Passage Round-Trip Tests
 *
 * Tests QTI → PIE transformation with passages that were generated by pie-to-qti2
 * Verifies that passage references and identifiers are preserved
 *
 * Note: Full round-trip (PIE → QTI → PIE) is tested in the integration test suite
 * that runs across both packages. These tests verify QTI → PIE specifically.
 */

import { describe, expect, test } from 'bun:test';
import type { TransformContext } from '@pie-qti/transform-types';
import { Qti22ToPiePlugin } from '../../src/plugin.js';

describe('QTI → PIE with External Passage References', () => {
  const plugin = new Qti22ToPiePlugin();

  const mockLogger = {
    info: () => {},
    warn: () => {},
    error: () => {},
    debug: () => {},
  };
  const context: TransformContext = { logger: mockLogger };

  test('should extract passage reference from QTI generated by pie-to-qti2', async () => {
    // This QTI was generated by pie-to-qti2 from a PIE item with passage: 'passage-external-123'
    const qtiFromPieToQti2 = `<?xml version="1.0" encoding="UTF-8"?>
<assessmentItem xmlns="http://www.imsglobal.org/xsd/imsqti_v2p2"
                identifier="item-rt-1"
                title="Question"
                adaptive="false"
                timeDependent="false">
  <itemBody>
    <object data="passages/passage-external-123.xml"
            type="text/html"
            data-pie-passage-id="passage-external-123">
      <p>Passage content not available</p>
    </object>

    <choiceInteraction responseIdentifier="RESPONSE" maxChoices="1">
      <prompt>Based on the passage, what is the main idea?</prompt>
      <simpleChoice identifier="choice-0">Choice A</simpleChoice>
      <simpleChoice identifier="choice-1">Choice B</simpleChoice>
    </choiceInteraction>
  </itemBody>

  <responseDeclaration identifier="RESPONSE" cardinality="single" baseType="identifier">
    <correctResponse>
      <value>choice-0</value>
    </correctResponse>
  </responseDeclaration>
</assessmentItem>`;

    const result = await plugin.transform({ content: qtiFromPieToQti2 }, context);

    expect(result.items.length).toBe(1);
    const pieItem = result.items[0].content;

    // Should restore passage property
    expect(pieItem.passage).toBe('passage-external-123');

    // Should also have passage model in config.models
    expect(pieItem.config.models.length).toBe(2); // passage + mc
    expect(pieItem.config.models[0].element).toBe('@pie-element/passage');
  });

  test('should handle QTI with baseId in passage reference', async () => {
    const qtiWithBaseId = `<?xml version="1.0" encoding="UTF-8"?>
<assessmentItem xmlns="http://www.imsglobal.org/xsd/imsqti_v2p2"
                identifier="item-stable-id"
                title="Question"
                adaptive="false"
                timeDependent="false">
  <itemBody>
    <object data="passages/passage-stable-789.xml"
            type="text/html"
            data-pie-passage-id="passage-stable-789">
      <p>Fallback</p>
    </object>

    <choiceInteraction responseIdentifier="RESPONSE" maxChoices="1">
      <prompt>Question?</prompt>
      <simpleChoice identifier="a">A</simpleChoice>
    </choiceInteraction>
  </itemBody>

  <responseDeclaration identifier="RESPONSE" cardinality="single" baseType="identifier">
    <correctResponse>
      <value>a</value>
    </correctResponse>
  </responseDeclaration>
</assessmentItem>`;

    const result = await plugin.transform({ content: qtiWithBaseId }, context);

    const pieItem = result.items[0].content;

    // Passage reference preserved
    expect(pieItem.passage).toBe('passage-stable-789');
  });

  test('should NOT set passage property for inline stimulus', async () => {
    // QTI generated from PIE item with inline passage (in config.models)
    // Uses <stimulus> tag for inline content (not <object> reference)
    const qtiWithInlineStimulus = `<?xml version="1.0" encoding="UTF-8"?>
<assessmentItem xmlns="http://www.imsglobal.org/xsd/imsqti_v2p2"
                identifier="item-inline"
                title="Question"
                adaptive="false"
                timeDependent="false">
  <itemBody>
    <stimulus>
      <h2>Inline Passage</h2>
      <p>This passage is embedded inline in the item.</p>
    </stimulus>

    <choiceInteraction responseIdentifier="RESPONSE" maxChoices="1">
      <prompt>Question about inline passage?</prompt>
      <simpleChoice identifier="a">Yes</simpleChoice>
    </choiceInteraction>
  </itemBody>

  <responseDeclaration identifier="RESPONSE" cardinality="single" baseType="identifier">
    <correctResponse>
      <value>a</value>
    </correctResponse>
  </responseDeclaration>
</assessmentItem>`;

    const result = await plugin.transform({ content: qtiWithInlineStimulus }, context);

    const pieItem = result.items[0].content;

    // Should NOT populate passage property for inline stimulus
    expect(pieItem.passage).toBeUndefined();

    // But should have passage model
    const passageModel = pieItem.config.models.find(m => m.element === '@pie-element/passage');
    expect(passageModel).toBeTruthy();
  });

  test('should preserve passage ID through QTI object reference', async () => {
    // This documents the complete flow:
    // 1. PIE item has: passage: "custom-passage-id"
    // 2. pie-to-qti2 generates: <object data="passages/custom-passage-id.xml" data-pie-passage-id="custom-passage-id">
    // 3. qti2-to-pie restores: passage: "custom-passage-id"

    const qtiWithCustomId = `<?xml version="1.0" encoding="UTF-8"?>
<assessmentItem xmlns="http://www.imsglobal.org/xsd/imsqti_v2p2"
                identifier="test-item"
                title="Test">
  <itemBody>
    <object data="passages/custom-passage-id.xml"
            type="text/html"
            data-pie-passage-id="custom-passage-id"/>

    <choiceInteraction responseIdentifier="RESPONSE" maxChoices="1">
      <prompt>Q?</prompt>
      <simpleChoice identifier="a">A</simpleChoice>
    </choiceInteraction>
  </itemBody>

  <responseDeclaration identifier="RESPONSE" cardinality="single" baseType="identifier">
    <correctResponse>
      <value>a</value>
    </correctResponse>
  </responseDeclaration>
</assessmentItem>`;

    const result = await plugin.transform({ content: qtiWithCustomId }, context);

    const pieItem = result.items[0].content;

    // Custom passage ID preserved
    expect(pieItem.passage).toBe('custom-passage-id');
  });
});
