/**
 * BaseId Extraction Utilities
 *
 * Extracts stable/public identifiers (baseId) from QTI metadata for round-trip compatibility
 */

import type { HTMLElement } from 'node-html-parser';

/**
 * Extract baseId from QTI metadata
 *
 * Checks for baseId in qti-metadata-field with name="externalId" or name="baseId"
 * This supports round-trip compatibility with pie-to-qti2 which sets:
 * - sourceSystemId = "pie"
 * - externalId = baseId (if present) or id (fallback)
 *
 * @param itemElement - The assessmentItem element
 * @returns baseId if found, undefined otherwise
 */
export function extractBaseId(itemElement: HTMLElement): string | undefined {
  // Look for qti-metadata section
  const qtiMetadata = itemElement.querySelector('qti-metadata') ||
                     itemElement.getElementsByTagName('qti-metadata')[0];

  if (!qtiMetadata) {
    return undefined;
  }

  // Look for metadata fields
  const metadataFields = qtiMetadata.getElementsByTagName('qti-metadata-field');

  for (const field of Array.from(metadataFields)) {
    const name = field.getAttribute('name');
    const value = field.getAttribute('value');

    // Check for externalId (pie-to-qti2 convention)
    if (name === 'externalId' && value) {
      // Verify this came from PIE by checking sourceSystemId
      const sourceField = Array.from(metadataFields).find(
        f => f.getAttribute('name') === 'sourceSystemId'
      );

      if (sourceField?.getAttribute('value') === 'pie') {
        // This is a PIE-generated baseId/externalId
        return value;
      }
    }

    // Check for explicit baseId field
    if (name === 'baseId' && value) {
      return value;
    }
  }

  return undefined;
}

/**
 * Extract both id and baseId from QTI assessmentItem
 *
 * @param itemElement - The assessmentItem element
 * @returns Object with id (from identifier attribute) and optional baseId (from metadata)
 */
export function extractIdentifiers(itemElement: HTMLElement): { id: string; baseId?: string } {
  // Get identifier attribute (required in QTI)
  const id = itemElement.getAttribute('identifier') || `item-${Date.now()}`;

  // Get baseId from metadata (optional)
  const baseId = extractBaseId(itemElement);

  return { id, baseId };
}

/**
 * Determine if a QTI item was generated by pie-to-qti2
 *
 * Checks for PIE namespace and sourceSystemId metadata
 *
 * @param itemElement - The assessmentItem element
 * @returns true if item appears to be PIE-generated
 */
export function isPieGenerated(itemElement: HTMLElement): boolean {
  // Check for pie: namespace in attributes
  const itemHtml = itemElement.toString();
  if (itemHtml.includes('xmlns:pie=') || itemHtml.includes('pie:sourceModel')) {
    return true;
  }

  // Check for sourceSystemId="pie" in metadata
  const qtiMetadata = itemElement.querySelector('qti-metadata') ||
                     itemElement.getElementsByTagName('qti-metadata')[0];

  if (qtiMetadata) {
    const metadataFields = qtiMetadata.getElementsByTagName('qti-metadata-field');
    for (const field of Array.from(metadataFields)) {
      if (field.getAttribute('name') === 'sourceSystemId' &&
          field.getAttribute('value') === 'pie') {
        return true;
      }
    }
  }

  return false;
}
