/**
 * Metadata Extraction Utilities
 *
 * Extracts searchMetaData and other metadata from QTI items
 */

import type { HTMLElement } from 'node-html-parser';
import { parse } from 'node-html-parser';

/**
 * Extract searchMetaData from QTI item
 *
 * Priority 1: Check for PIE extension with embedded searchMetaData (perfect reconstruction)
 * Priority 2: Parse QTI metadata section
 *
 * @param qtiXml - QTI XML string or parsed HTMLElement
 * @returns Extracted searchMetaData object
 */
export function extractSearchMetadata(qtiXml: string | HTMLElement): Record<string, any> {
  // Parse if needed
  const doc = typeof qtiXml === 'string'
    ? parse(qtiXml, { lowerCaseTagName: false, comment: false })
    : qtiXml;

  // Priority 1: Try PIE extension first (perfect reconstruction)
  const pieExtension = doc.querySelector('pie\\:sourceModel') ||
                       Array.from(doc.getElementsByTagName('*'))
                         .find(el => el.rawTagName === 'pie:sourceModel');

  if (pieExtension) {
    try {
      const sourceModelText = pieExtension.textContent || pieExtension.innerHTML;
      const sourceModel = JSON.parse(sourceModelText);
      if (sourceModel.searchMetaData) {
        return sourceModel.searchMetaData;
      }
    } catch (e) {
      // Fall through to QTI metadata parsing
    }
  }

  // Priority 2: Parse <qti-metadata> section
  const metadata: Record<string, any> = {};
  const metadataSection = doc.querySelector('qti-metadata') ||
                          doc.getElementsByTagName('qti-metadata')[0];

  if (metadataSection) {
    const fields = metadataSection.querySelectorAll('qti-metadata-field') ||
                   metadataSection.getElementsByTagName('qti-metadata-field');

    for (const field of Array.from(fields)) {
      const name = field.getAttribute('name');
      const value = field.getAttribute('value');
      const dataType = field.getAttribute('data-type');

      if (!name || value === null || value === undefined) continue;

      // Restore original type
      if (dataType === 'array') {
        metadata[name] = value.split(',').map(v => v.trim());
      } else if (dataType === 'number') {
        metadata[name] = parseFloat(value);
      } else {
        metadata[name] = value;
      }
    }
  }

  return metadata;
}

/**
 * Merge extracted searchMetaData with transformer-generated metadata
 *
 * @param extractedMetadata - Metadata from QTI XML
 * @param transformerMetadata - Metadata generated by transformer
 * @returns Merged metadata (extracted takes precedence)
 */
export function mergeSearchMetadata(
  extractedMetadata: Record<string, any>,
  transformerMetadata: Record<string, any>
): Record<string, any> {
  // Extracted metadata takes precedence
  return {
    ...transformerMetadata,
    ...extractedMetadata,
  };
}
